experiment_name: 'cifar10-alexnet'

dataset:
    name: 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

model:
    type: 'alexnet'
    ckpt: './resource/ckpt/alexnet.ckpt'
    params:
        num_classes: 10
        # additional parameters for CIFAR-10 and -100
        first_conv2d_ksize: 2
        first_conv2d_stride: 1
        first_conv2d_padding: 1
        last_maxpool2d_ksize: 2
        last_maxpool2d_stride: 1
