experiment_name: 'cifar10-densenet'

dataset: 'cifar10'

input_shape: [3, 32, 32]

model:
    type: 'densenet'
    params:
        growth_rate: 12
        block_config: [6, 12, 24, 16]
        num_init_features: 64
        bn_size: 4
        drop_rate: 0
        num_classes: 10
        # additional parameters for CIFAR-10
        conv2d_ksize: 2
        conv2d_stride: 1
        conv2d_padding: 1
        maxpool_2d_ksize: 2
        maxpool_2d_stride: 2
        maxpool_2d_padding: 1
        avg_pool2d_ksize: 2
