experiment_name: 'caltech101-densenet169'

dataset:
    name: 'caltech101'
    data: './resource/data/caltech101/'

input_shape: [3, 240, 240]

model:
    type: 'densenet'
    ckpt: './resource/ckpt/densenet169.ckpt'
    params:
        growth_rate: 32
        block_config: [6, 12, 32, 32]
        num_init_features: 64
        bn_size: 4
        drop_rate: 0
        num_classes: 101
        # additional parameters for Caltech101 and 256
        conv2d_ksize: 7
        conv2d_stride: 2
        conv2d_padding: 3
        maxpool_2d_ksize: 3
        maxpool_2d_stride: 2
        maxpool_2d_padding: 1
        avg_pool2d_ksize: 7

train:
    epoch: 50
    batch_size: 20
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
    autoencoder: