dataset:
    name: &dataset_name 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

model:
    type: &model_type 'lenet5'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        num_classes: 10
