dataset:
    name: &dataset_name 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

model:
    type: &model_type 'resnet18'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        num_classes: 10
        # additional parameters for CIFAR-10 and -100
        first_conv2d_ksize: 6
        first_conv2d_stride: 2
        first_conv2d_padding: 3
        last_avgpool2d_ksize: 2
        last_avgpool2d_stride: 1
