dataset:
    name: &dataset_name 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

autoencoder:
    type: &model_type 'vae'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        hidden_size: 20
        intermediate_size: 128

train:
    epoch: 50
    batch_size: 100
    interval: 50
    optimizer:
        type: 'RMSprop'
        params:
            lr: 0.01
