dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']

input_shape: [3, 224, 224]

model:
    type: &model_type 'vgg16'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']

train:
    epoch: 50
    batch_size: 20
    rough_size: [256, 256]
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
    autoencoder:
