dataset:
    name: &dataset_name 'caltech101'
    data: './resource/data/caltech101/'

input_shape: [3, 224, 224]

model:
    type: &model_type 'vgg16'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
