dataset:
    name: &dataset_name 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

model:
    type: &model_type 'densenet121'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        growth_rate: 12
        block_config: [6, 12, 24, 16]
        num_init_features: 64
        bn_size: 4
        drop_rate: 0
        num_classes: 10
        # additional parameters for CIFAR-10 and -100
        conv2d_ksize: 2
        conv2d_stride: 1
        conv2d_padding: 1
        maxpool_2d_ksize: 2
        maxpool_2d_stride: 2
        maxpool_2d_padding: 1
        avg_pool2d_ksize: 2

train:
    epoch: 50
    batch_size: 100
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type: None
        size: None
    autoencoder: None
