dataset:
    name: &dataset_name 'cifar10'
    data: './resource/data/'

input_shape: [3, 32, 32]

model:
    type: &model_type 'resnet18'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    ckpt: !join ['./resource/ckpt/', *experiment, '.pt']
    params:
        num_classes: 10
        # additional parameters for CIFAR-10 and -100
        first_conv2d_ksize: 6
        first_conv2d_stride: 2
        first_conv2d_padding: 3
        last_avgpool2d_ksize: 2
        last_avgpool2d_stride: 1

train:
    epoch: 50
    batch_size: 100
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
