dataset:
    name: &dataset_name 'cifar100'
    root: &data_dir './resource/data/cifar100/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'valid.txt']
    normalizer:
        mean: [0.5070751592371323, 0.48654887331495095, 0.4409178433670343]
        std: [0.2673342858792401, 0.2564384629170883, 0.27615047132568404]

input_shape: [3, 32, 32]

model:
    type: &model_type 'resnet50'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    pretrained: True
    load_model: True
    weights: !join ['./resource/pt/', *dataset_name, '-', *model_type, '-32.pt']
    ckpt: !join ['./resource/ckpt/', *experiment, '.pt']
    params:
        num_classes: 100
        #num_init_features: 64
        #first_conv2d_ksize: 7
        #first_conv2d_stride: 2
        #first_conv2d_padding: 3
        #last_avgpool2d_ksize: 7
        #last_avgpool2d_stride: 1

train:
    epoch: 50
    batch_size: 20
    rough_size: 256
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
    autoencoder:
