experiment_name: 'caltech101-student-densenet121'

dataset:
    name: 'caltech101'
    train: './resource/data/'
    test: './resource/data/caltech101/test/'

input_shape: [3, 240, 240]

teacher_model:
    config: './config/densenet-cal.yaml'
    start_idx: 0
    end_idx: 118

student_model:
    type: 'densenet121_head_mimic'
    ckpt: './resource/ckpt/student/densenet121_head_mimic.ckpt'

train:
    epoch: 50
    batch_size: 20
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            learn_late: 0.01
    loss:
        type: 'mse'
        params:
            reduction: 'sum'
