dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean:
        std:

input_shape: [3, 299, 299]

teacher_model:
    config: './config/inception_v3.yaml'
    extract_designed_module: False
    start_idx: 0
    end_idx: 17 # 17, 21, 26 for vers. 1, 2, 3

student_model:
    type: &smodel_type 'inception_v3_head_mimic'
    version: &ver '1b'
    experiment: &distill_experiment !join [*dataset_name, '-', *smodel_type, '-ver', *ver]
    ckpt: !join ['./resource/ckpt/mimic/', *distill_experiment, '.ckpt']

mimic_model:
    type: &mmodel_type 'inception_v3_mimic'
    experiment: &mimic_experiment !join [*dataset_name, '-', *mmodel_type, '-ver', *ver]
    ckpt: !join ['./resource/model/mimic/', *mimic_experiment, '.pkl']

train:
    epoch: 100
    batch_size: 20
    rough_size: [327, 327]
    interval: -1
    optimizer:
        type: 'Adam'
        params:
            lr: 0.01
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'sum'

test:
    batch_size: 1
