dataset:
    name: &dataset_name 'caltech101'
    data: './resource/data/caltech101/'

input_shape: [3, 240, 240]

teacher_model:
    config: './config/vgg16.yaml'
    extract_designed_module: False
    start_idx: 0
    end_idx: 8

student_model:
    type: &smodel_type 'vgg16_head_mimic'
    experiment: &distil_experiment !join [*dataset_name, '-', *smodel_type]
    ckpt: !join ['./resource/ckpt/mimic/', *distil_experiment, '.ckpt']

mimic_model:
    type: &mmodel_type 'vgg16_mimic'
    experiment: &mimic_experiment !join [*dataset_name, '-', *mmodel_type]
    ckpt: !join ['./resource/model/mimic/', *mimic_experiment, '.pkl']

train:
    epoch: 50
    batch_size: 20
    interval: 50
    optimizer:
        type: 'adam'
        params:
            lr: 0.01
    criterion:
        type: 'mse'
        params:
            reduction: 'sum'

test:
    batch_size: 1
