dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean:
        std:

input_shape: [3, 224, 224]

teacher_model:
    config: './config/vgg16.yaml'
    extract_designed_module: False
    start_idx: 0
    end_idx: 8

student_model:
    type: &smodel_type 'vgg16_head_mimic'
    experiment: &distill_experiment !join [*dataset_name, '-', *smodel_type]
    ckpt: !join ['./resource/ckpt/mimic/', *distill_experiment, '.ckpt']

mimic_model:
    type: &mmodel_type 'vgg16_mimic'
    experiment: &mimic_experiment !join [*dataset_name, '-', *mmodel_type]
    ckpt: !join ['./resource/model/mimic/', *mimic_experiment, '.pkl']

train:
    epoch: 100
    batch_size: 20
    rough_size: [256, 256]
    interval: -1
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'sum'

test:
    batch_size: 1
